### ISSUE TITLE
Tag a stable version number for Homebrew.

### ISSUE THREAD

**Issue by adamv** [tcurdt/authexec#1]
Homebrew packages this as a head-only formula. We would appreciate it if a stable version could be tagged, so we can use that tarball instead of HEAD.

**Comment by tcurdt** [comment]
Sure. Done. https://github.com/tcurdt/authexec/tags

**Comment by tcurdt** [comment]
Will you update the formula?

**Comment by adamv** [comment]
Updated, thanks!
